name: tilt
description: Easy access to the current tilt on `x` and `y` axis.
version: 0.0.2
repository: https://github.com/pijaro/flutter-tilt

environment:
  sdk: ">=2.11.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: 0.6.0
  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.recki.tilt
        pluginClass: TiltPlugin
      ios:
        pluginClass: TiltPlugin
